version: '3.3'
services:
  ui:
    image: apache/skywalking-ui:7.0.0
    container_name: ui
    restart: always
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: 192.168.24.164:12800,192.168.24.164:12801,192.168.24.164:12802